
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Automatically register all classes in src/ as services
    App\:
        resource: '../src/'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Service\EmailService:
        arguments:
            $fromEmail: '%env(DEFAULT_FROM_EMAIL)%'
            $logger: '@monolog.logger'

    App\Security\JwtAuthenticator:
        autowire: true
        autoconfigure: true
        tags:
            - { name: security.authenticator }
